/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : Port_E_H_Init_GPIO.h
**     Project     : BMU_113_BSW_ZB_20S
**     Processor   : SKEAZ128MLK4
**     Component   : Init_GPIO
**     Version     : Component 01.006, Driver 01.06, CPU db: 3.00.000
**     Repository  : Kinetis
**     Compiler    : GNU C Compiler
**     Date/Time   : 2017-12-08, 19:16, # CodeGen: 20
**     Abstract    :
**          This file implements the GPIO (GPIOB) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
**     Settings    :
**          Component name                                 : Port_E_H_Init_GPIO
**          Device                                         : GPIOB
**          Settings                                       : 
**            Clock gate                                   : Enabled
**            Pin 0                                        : Do not initialize
**            Pin 1                                        : Do not initialize
**            Pin 2                                        : Do not initialize
**            Pin 3                                        : Initialize
**              Pin direction                              : Output
**              Pin input                                  : Disabled
**              Output value                               : 1
**              Pull resistor                              : <Automatic>
**            Pin 4                                        : Initialize
**              Pin direction                              : Output
**              Pin input                                  : Disabled
**              Output value                               : 1
**              Pull resistor                              : <Automatic>
**            Pin 5                                        : Initialize
**              Pin direction                              : Input
**              Pin input                                  : Enabled
**              Output value                               : 0
**              Pull resistor                              : <Automatic>
**            Pin 6                                        : Initialize
**              Pin direction                              : Input
**              Pin input                                  : Enabled
**              Output value                               : 0
**              Pull resistor                              : <Automatic>
**            Pin 7                                        : Initialize
**              Pin direction                              : Output
**              Pin input                                  : Disabled
**              Output value                               : 1
**              Pull resistor                              : <Automatic>
**            Pin 8                                        : Initialize
**              Pin direction                              : Input
**              Pin input                                  : Enabled
**              Output value                               : 0
**              Pull resistor                              : <Automatic>
**            Pin 9                                        : Do not initialize
**            Pin 10                                       : Initialize
**              Pin direction                              : Output
**              Pin input                                  : Disabled
**              Output value                               : 0
**              Pull resistor                              : <Automatic>
**            Pin 11                                       : Initialize
**              Pin direction                              : Output
**              Pin input                                  : Disabled
**              Output value                               : 0
**              Pull resistor                              : <Automatic>
**            Pin 12                                       : Do not initialize
**            Pin 13                                       : Do not initialize
**            Pin 14                                       : Do not initialize
**            Pin 15                                       : Do not initialize
**            Pin 16                                       : Initialize
**              Pin direction                              : Output
**              Pin input                                  : Disabled
**              Output value                               : 0
**              Pull resistor                              : <Automatic>
**            Pin 17                                       : Initialize
**              Pin direction                              : Output
**              Pin input                                  : Disabled
**              Output value                               : 0
**              Pull resistor                              : <Automatic>
**            Pin 18                                       : Initialize
**              Pin direction                              : Output
**              Pin input                                  : Disabled
**              Output value                               : 0
**              Pull resistor                              : <Automatic>
**            Pin 19                                       : Initialize
**              Pin direction                              : Output
**              Pin input                                  : Disabled
**              Output value                               : 0
**              Pull resistor                              : <Automatic>
**            Pin 20                                       : Do not initialize
**            Pin 21                                       : Do not initialize
**            Pin 22                                       : Do not initialize
**            Pin 23                                       : Initialize
**              Pin direction                              : Output
**              Pin input                                  : Disabled
**              Output value                               : 1
**              Pull resistor                              : <Automatic>
**            Pin 24                                       : Initialize
**              Pin direction                              : Output
**              Pin input                                  : Disabled
**              Output value                               : 0
**              Pull resistor                              : <Automatic>
**            Pin 25                                       : Initialize
**              Pin direction                              : Output
**              Pin input                                  : Disabled
**              Output value                               : 0
**              Pull resistor                              : <Automatic>
**            Pin 26                                       : Initialize
**              Pin direction                              : Output
**              Pin input                                  : Disabled
**              Output value                               : 0
**              Pull resistor                              : <Automatic>
**            Pin 27                                       : Initialize
**              Pin direction                              : Output
**              Pin input                                  : Disabled
**              Output value                               : 0
**              Pull resistor                              : <Automatic>
**            Pin 28                                       : Initialize
**              Pin direction                              : Output
**              Pin input                                  : Disabled
**              Output value                               : 0
**              Pull resistor                              : <Automatic>
**            Pin 29                                       : Initialize
**              Pin direction                              : Output
**              Pin input                                  : Disabled
**              Output value                               : 0
**              Pull resistor                              : <Automatic>
**            Pin 30                                       : Initialize
**              Pin direction                              : Output
**              Pin input                                  : Disabled
**              Output value                               : 0
**              Pull resistor                              : <Automatic>
**            Pin 31                                       : Do not initialize
**          Pin selection/routing                          : 
**            Pin 0                                        : Disabled
**            Pin 1                                        : Disabled
**            Pin 2                                        : Disabled
**            Pin 3                                        : Disabled
**            Pin 4                                        : Disabled
**            Pin 5                                        : Disabled
**            Pin 6                                        : Disabled
**            Pin 7                                        : Disabled
**            Pin 8                                        : Disabled
**            Pin 9                                        : Disabled
**            Pin 10                                       : Disabled
**            Pin 11                                       : Disabled
**            Pin 12                                       : Disabled
**            Pin 13                                       : Disabled
**            Pin 14                                       : Disabled
**            Pin 15                                       : Disabled
**            Pin 16                                       : Disabled
**            Pin 17                                       : Disabled
**            Pin 18                                       : Disabled
**            Pin 19                                       : Disabled
**            Pin 20                                       : Disabled
**            Pin 21                                       : Disabled
**            Pin 22                                       : Disabled
**            Pin 23                                       : Disabled
**            Pin 24                                       : Disabled
**            Pin 25                                       : Disabled
**            Pin 26                                       : Disabled
**            Pin 27                                       : Disabled
**            Pin 28                                       : Disabled
**            Pin 29                                       : Disabled
**            Pin 30                                       : Disabled
**            Pin 31                                       : Disabled
**          Initialization                                 : 
**            Call Init method                             : yes
**            Utilize after reset values                   : default
**     Contents    :
**         Init - void Port_E_H_Init_GPIO_Init(void);
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file Port_E_H_Init_GPIO.h
** @version 01.06
** @brief
**          This file implements the GPIO (GPIOB) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
*/         
/*!
**  @addtogroup Port_E_H_Init_GPIO_module Port_E_H_Init_GPIO module documentation
**  @{
*/         

#ifndef Port_E_H_Init_GPIO_H_
#define Port_E_H_Init_GPIO_H_

/* MODULE Port_E_H_Init_GPIO. */

#include "GPIOB_Init.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Initialization method user name */
#define Port_E_H_Init_GPIO_Init GPIOB_Init
/* PDD macros peripheral base address parameter */
#define Port_E_H_Init_GPIO_DEVICE GPIOB_BASE_PTR

#ifdef __cplusplus
}
#endif

/* END Port_E_H_Init_GPIO. */
#endif /* #ifndef __Port_E_H_Init_GPIO_H_ */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/


